### ISSUE TITLE
Ensure the hosts_allow and hosts_deny resources cover the 'optional' and extended cases 

### ISSUE THREAD

**Issue by aaronlippold** [jburns12/inspec_profiles#15]
see: https://www.centos.org/docs/rhel-rg-en-3/s1-tcpwrappers-access.html 

Sections : 16.2.x

**Comment by aaronlippold** [comment]
wooo hooo - my hair is pointy ...

**Comment by dromazmj** [comment]
Implemented with the 'option' attribute, which is a list of all options pertaining to a rule.
