### ISSUE TITLE
V-71999 - Verify the OS security patches and updates are installed and up to date.

### ISSUE THREAD

**Issue by jburns12** [jburns12/inspec_profiles#6]
This control needs to be implemented to check package versions against a list of available package security updates from Red Hat at https://rhn.redhat.com/errata.

**Comment by aaronlippold** [comment]
See: https://github.com/dev-sec/linux-patch-baseline

**Comment by jburns12** [comment]
Implemented control and added linux_updates resource as found in above link. commit - 6d0a1fc4f569f28d2b08602c80e2644b3eb9e74f
